apiVersion: v1
kind: Service
metadata:
  name: vue-app
  labels:
    run: vue-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  externalIPs: 
    - 192.168.1.63
  selector:
    run: vue-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: vue-app
    spec:
      containers:
      - name: vue-app
        image: magikcypress/vue-app
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vue-app
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: vue-app
          servicePort: 80
